### PR TITLE
flake: eachDefaultSystem

### PR DESCRIPTION
**Pull request by alissa-tung**
```
% nix flake show 'github:nomeata/loogle'
github:nomeata/loogle/67069bd25435e5d42ed928ac88828edfed495d18
├───devShells
│   └───x86_64-linux
│       └───default omitted (use '--all-systems' to show)
├───nixosConfigurations
│   └───loogle: NixOS configuration
└───packages
    └───x86_64-linux
        ├───default omitted (use '--all-systems' to show)
        ├───loogle omitted (use '--all-systems' to show)
        ├───loogle_exe omitted (use '--all-systems' to show)
        ├───loogle_index omitted (use '--all-systems' to show)
        ├───loogle_seccomp omitted (use '--all-systems' to show)
        ├───loogle_server omitted (use '--all-systems' to show)
        └───mathlib omitted (use '--all-systems' to show)

% nix flake show 'github:alissa-tung/loogle'
git+file:///Users/alissa/pod/loogle
├───devShells
│   ├───aarch64-darwin
│   │   └───default: development environment 'nix-shell'
│   ├───aarch64-linux
│   │   └───default omitted (use '--all-systems' to show)
│   ├───x86_64-darwin
│   │   └───default omitted (use '--all-systems' to show)
│   └───x86_64-linux
│       └───default omitted (use '--all-systems' to show)
├───nixosConfigurations
│   └───loogle: NixOS configuration
└───packages
    ├───aarch64-darwin
    │   ├───default: package 'loogle'
    │   ├───loogle: package 'loogle'
    │   ├───loogle_exe: package 'loogle'
    │   ├───loogle_index: package 'loogle.index'
    │   ├───loogle_seccomp: package 'loogle_seccomp'
    │   ├───loogle_server: package 'loogle_server'
    │   └───mathlib: package 'Mathlib'
    ├───aarch64-linux
    │   ├───default omitted (use '--all-systems' to show)
    │   ├───loogle omitted (use '--all-systems' to show)
    │   ├───loogle_exe omitted (use '--all-systems' to show)
    │   ├───loogle_index omitted (use '--all-systems' to show)
    │   ├───loogle_seccomp omitted (use '--all-systems' to show)
    │   ├───loogle_server omitted (use '--all-systems' to show)
    │   └───mathlib omitted (use '--all-systems' to show)
    ├───x86_64-darwin
    │   ├───default omitted (use '--all-systems' to show)
    │   ├───loogle omitted (use '--all-systems' to show)
    │   ├───loogle_exe omitted (use '--all-systems' to show)
    │   ├───loogle_index omitted (use '--all-systems' to show)
    │   ├───loogle_seccomp omitted (use '--all-systems' to show)
    │   ├───loogle_server omitted (use '--all-systems' to show)
    │   └───mathlib omitted (use '--all-systems' to show)
    └───x86_64-linux
        ├───default omitted (use '--all-systems' to show)
        ├───loogle omitted (use '--all-systems' to show)
        ├───loogle_exe omitted (use '--all-systems' to show)
        ├───loogle_index omitted (use '--all-systems' to show)
        ├───loogle_seccomp omitted (use '--all-systems' to show)
        ├───loogle_server omitted (use '--all-systems' to show)
        └───mathlib omitted (use '--all-systems' to show)
```

### CODE REVIEW

**Comment by alissa-tung** [comment]
This PR aims at running the loogle cli on many platforms. I have not test the server config.

**Comment by nomeata** [comment]
Thanks! Does the `loogle` CLI work on all these platforms, in particular the seccomp stuff?

**Comment by alissa-tung** [comment]
> Thanks! Does the `loogle` CLI work on all these platforms, in particular the seccomp stuff?

oh sorry，i forgot to mention，i am trying to fix on aarch-Darwin。since ccache on darwin at the commit of nixpkgs of this repo is broken（the checkPhase），i am still trying to write some overlays to fix and test it…

**Comment by alissa-tung** [comment]
seems that you have bumped the deps version，i can rebase and test the Darwin cli.！the linux one is not easy for me right now and also the server part.

**Comment by nomeata** [comment]
Sorry for the conflict.

Would be good to know if this is expected to work, in case someone asks :-D

**Comment by alissa-tung** [comment]
Seems that `ccache-4.8.1 (checkPhase)` on `aarch64-darwin` is still broken. Do you think we need should write a overlay for it?

**Comment by nomeata** [comment]
You mean the `ccache` package itself is broken, in nixpkgs?

**Comment by alissa-tung** [comment]
> You mean the `ccache` package itself is broken, in nixpkgs?

There is no binary cache for aarch64-darwin `ccache` from nixpkgs when running `nix run .#loogle -- --help`, so it needs to build from source and do the check phase, which will fail

**Comment by nomeata** [comment]
I see. But that means that `nix  run github:leanprover/lean4` fails the same way, right, and it’s an issue at least with nix setup in the lean repo, if not with nixpkgs itself?

If you can reproduce it with the lean4 repo, you could try to see if upgrading `nixpkgs` there makes the issue go away. Else I fear there is a rabbit hole waiting…

**Comment by alissa-tung** [comment]
> I see. But that means that `nix run github:leanprover/lean4` fails the same way, right, and it’s an issue at least with nix setup in the lean repo, if not with nixpkgs itself?
> 
> If you can reproduce it with the lean4 repo, you could try to see if upgrading `nixpkgs` there makes the issue go away. Else I fear there is a rabbit hole waiting…

It is quite easy to reproduce with `nix run github:leanprover/lean4`, almost instantly. The newer nixpkgs does not have this issue. Should we file a issue for bump the nixpkgs of Lean4?

**Comment by nomeata** [comment]
Yes, it's reasonable to create a PR against `lean4` that bumps the nixpkg pin

**Pull request closed without merging**
